# Generated by Django 3.2.4 on 2021-07-04 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('poster', models.ImageField(upload_to='posters')),
                ('views', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SongList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_list', models.FileField(upload_to='playlists')),
                ('title', models.CharField(default='', max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radiolive.playlist')),
            ],
        ),
    ]
