# Generated by Django 3.2.4 on 2021-07-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiolive', '0002_alter_playlist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=200),
        ),
    ]
