# Generated by Django 3.2.4 on 2021-07-05 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiolive', '0003_alter_playlist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='poster',
            field=models.ImageField(blank=True, default='1.png', upload_to='posters'),
        ),
    ]
